import { useEffect, useState } from 'react'
import { LUNA_PER_NIM } from '../../../shared/money'

type Sale = { id: string; itemSummary: string; status: string }
type SupportRequest = { id: string; purchaseId: string; status: 'OPEN' | 'IN_REVIEW' | 'RESOLVED'; message: string; createdAt: string }

const merchantStorageKey = 'nimpurchase:merchant-id'
const saleStatusLabel = (status: string) => ({ PAYMENT_PENDING: 'Waiting for payment', PAYMENT_SUBMITTED: 'Payment sent', PAYMENT_DETECTED: 'Securing purchase', ACTIVE: 'Verified sale', EXPIRED: 'Expired', PAYMENT_MISMATCH: 'Needs attention', PAYMENT_FAILED: 'Payment failed', CANCELLED: 'Cancelled' }[status] ?? status)
const supportStatusLabel = (status: SupportRequest['status']) => ({ OPEN: 'Open', IN_REVIEW: 'In review', RESOLVED: 'Resolved' }[status])

export function MerchantPage() {
  const [merchantId, setMerchantId] = useState(() => window.localStorage.getItem(merchantStorageKey) ?? ''); const [link, setLink] = useState(''); const [error, setError] = useState(''); const [sales, setSales] = useState<Sale[]>([]); const [support, setSupport] = useState<SupportRequest[]>([]); const [copied, setCopied] = useState(false)
  async function loadWorkspace(): Promise<void> {
    if (!merchantId) return
    const [salesResponse, supportResponse] = await Promise.all([fetch(`/api/merchants/${merchantId}/purchases`), fetch(`/api/merchants/${merchantId}/support`)])
    if (!salesResponse.ok || !supportResponse.ok) throw new Error('We could not refresh your merchant workspace.')
    setSales(await salesResponse.json() as Sale[]); setSupport(await supportResponse.json() as SupportRequest[])
  }
  useEffect(() => { void loadWorkspace().catch((reason: unknown) => setError(reason instanceof Error ? reason.message : 'We could not refresh your merchant workspace.')) }, [merchantId, link])
  async function merchant(form: HTMLFormElement) { const d = new FormData(form); const r = await fetch('/api/merchants', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ displayName: d.get('name'), walletAddress: d.get('wallet') }) }); const b = await r.json(); if (!r.ok) throw new Error(b.error); window.localStorage.setItem(merchantStorageKey, b.id); setMerchantId(b.id) }
  async function checkout(form: HTMLFormElement) { const d = new FormData(form); const nim = Number(d.get('price')); if (!Number.isFinite(nim) || !Number.isSafeInteger(nim * LUNA_PER_NIM)) throw new Error('Enter a price with at most five decimal places.'); const r = await fetch(`/api/merchants/${merchantId}/purchases`, { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ itemName: d.get('item'), priceLuna: Math.round(nim * LUNA_PER_NIM), warrantyNote: d.get('note'), threshold: Number(d.get('threshold')) || 5, rewardDescription: d.get('reward') }) }); const b = await r.json() as { checkoutPath: string; checkoutUrl?: string; error?: string }; if (!r.ok) throw new Error(b.error); setLink(b.checkoutUrl ?? `${window.location.origin}${b.checkoutPath}`); form.reset() }
  async function updateSupport(requestId: string, status: SupportRequest['status']): Promise<void> {
    const response = await fetch(`/api/merchants/${merchantId}/support/${requestId}`, { method: 'PATCH', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ status }) })
    if (!response.ok) throw new Error('We could not update this support request.')
    await loadWorkspace()
  }
  function switchMerchant(): void { window.localStorage.removeItem(merchantStorageKey); setMerchantId(''); setSales([]); setSupport([]); setLink(''); setError('') }
  const submit = (fn: (form: HTMLFormElement) => Promise<void>) => (e: React.FormEvent<HTMLFormElement>) => { e.preventDefault(); setError(''); void fn(e.currentTarget).catch((x: Error) => setError(x.message)) }
  return <main className="app-shell merchant-page"><p className="eyebrow">Merchant workspace</p><h1>{merchantId ? 'Create a checkout' : 'Start selling with NIM.'}</h1><p className="page-intro">Create an item, share one link, then see the verified sale appear here.</p>
    {!merchantId ? <form className="form-card" onSubmit={submit(merchant)}><h2>Your receiving wallet</h2><label>Business name<input name="name" placeholder="Alike Coffee" required /></label><label>Nimiq receiving address<input name="wallet" placeholder="NQ…" required /></label><button>Create merchant profile</button></form> : <><div className="workspace-actions"><p>This workspace is saved on this browser.</p><button className="quiet-button" onClick={switchMerchant}>Use another merchant</button></div><form className="form-card" onSubmit={submit(checkout)}><h2>New payable purchase</h2><label>Item name<input name="item" placeholder="Flat white" required /></label><label>Price in NIM<input name="price" inputMode="decimal" placeholder="1.50" required /></label><label>Warranty or return note <em>optional</em><input name="note" placeholder="Ask us within 7 days" /></label><details><summary>Loyalty reward <em>optional</em></summary><label>Purchases needed<input name="threshold" inputMode="numeric" placeholder="5" /></label><label>Reward description<input name="reward" placeholder="Free coffee" /></label></details><button>Create checkout link</button></form>
    {link && <section className="share-card"><p className="eyebrow">Ready to share</p><h2>Checkout created</h2><p className="checkout-url">{link}</p><button onClick={() => void navigator.clipboard.writeText(link).then(() => setCopied(true))}>{copied ? 'Link copied' : 'Copy checkout link'}</button><a className="text-link" href={link}>Open checkout</a></section>}
    <section className="sales-section"><p className="eyebrow">Sales</p><h2>Recent purchases</h2>{sales.length ? <ul className="sales-list">{sales.map((sale) => <li key={sale.id}><span>{sale.itemSummary}</span><small>{saleStatusLabel(sale.status)}</small></li>)}</ul> : <p className="empty-copy">Your verified sales will appear here after customers pay.</p>}</section>
    <section className="support-inbox"><p className="eyebrow">Customer support</p><h2>Support requests</h2>{support.length ? <ul className="support-list">{support.map((request) => <li key={request.id}><div><p className="support-message">{request.message}</p><small>{new Intl.DateTimeFormat(undefined, { dateStyle: 'medium' }).format(new Date(request.createdAt))}</small></div><label className="support-status">Status<select value={request.status} onChange={(event) => void updateSupport(request.id, event.target.value as SupportRequest['status']).catch((reason: unknown) => setError(reason instanceof Error ? reason.message : 'We could not update this support request.'))}><option value="OPEN">{supportStatusLabel('OPEN')}</option><option value="IN_REVIEW">{supportStatusLabel('IN_REVIEW')}</option><option value="RESOLVED">{supportStatusLabel('RESOLVED')}</option></select></label></li>)}</ul> : <p className="empty-copy">No support requests yet. Customers can contact you from a verified purchase card.</p>}</section></>}{error && <p className="form-error" role="alert">{error}</p>}</main>
}
