import { useState } from 'react'
import { LUNA_PER_NIM } from '../../../shared/money'

export function MerchantPage() {
  const [merchantId, setMerchantId] = useState(''); const [link, setLink] = useState(''); const [error, setError] = useState('')
  async function createMerchant(form: HTMLFormElement) { const data = new FormData(form); const response = await fetch('/api/merchants', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ displayName: data.get('name'), walletAddress: data.get('wallet') }) }); const body = await response.json(); if (!response.ok) throw new Error(body.error); setMerchantId(body.id) }
  async function createPurchase(form: HTMLFormElement) { const data = new FormData(form); const nim = Number(data.get('price')); if (!Number.isFinite(nim) || !Number.isSafeInteger(nim * LUNA_PER_NIM)) throw new Error('Enter a price with at most five decimal places.'); const response = await fetch(`/api/merchants/${merchantId}/purchases`, { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ itemName: data.get('item'), priceLuna: Math.round(nim * LUNA_PER_NIM), warrantyNote: data.get('note'), threshold: Number(data.get('threshold')) || 5, rewardDescription: data.get('reward') }) }); const body = await response.json(); if (!response.ok) throw new Error(body.error); setLink(`${window.location.origin}${body.checkoutPath}`) }
  return <main className="app-shell"><p className="eyebrow">Merchant</p><h1>Create a payable purchase</h1>{!merchantId ? <form onSubmit={(event) => { event.preventDefault(); void createMerchant(event.currentTarget).catch((reason: Error) => setError(reason.message)) }}><input name="name" placeholder="Business name" required /><input name="wallet" placeholder="Nimiq receiving address" required /><button>Create merchant profile</button></form> : <form onSubmit={(event) => { event.preventDefault(); void createPurchase(event.currentTarget).catch((reason: Error) => setError(reason.message)) }}><input name="item" placeholder="Item name" required /><input name="price" placeholder="Price in NIM" inputMode="decimal" required /><input name="note" placeholder="Warranty or return note (optional)" /><input name="threshold" placeholder="Reward threshold (default 5)" inputMode="numeric" /><input name="reward" placeholder="Reward description" /><button>Create checkout</button></form>}{link && <p>Your checkout link: <a href={link}>{link}</a></p>}{error && <p role="alert">{error}</p>}</main>
}
