import { useEffect, useState } from 'react'
import { LUNA_PER_NIM } from '../../../shared/money'

type Sale = { id: string; itemSummary: string; status: string }

export function MerchantPage() {
  const [merchantId, setMerchantId] = useState(''); const [link, setLink] = useState(''); const [error, setError] = useState(''); const [sales, setSales] = useState<Sale[]>([]); const [copied, setCopied] = useState(false)
  useEffect(() => { if (merchantId) void fetch(`/api/merchants/${merchantId}/purchases`).then((r) => r.json()).then(setSales) }, [merchantId, link])
  async function merchant(form: HTMLFormElement) { const d = new FormData(form); const r = await fetch('/api/merchants', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ displayName: d.get('name'), walletAddress: d.get('wallet') }) }); const b = await r.json(); if (!r.ok) throw new Error(b.error); setMerchantId(b.id) }
  async function checkout(form: HTMLFormElement) { const d = new FormData(form); const nim = Number(d.get('price')); if (!Number.isFinite(nim) || !Number.isSafeInteger(nim * LUNA_PER_NIM)) throw new Error('Enter a price with at most five decimal places.'); const r = await fetch(`/api/merchants/${merchantId}/purchases`, { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ itemName: d.get('item'), priceLuna: Math.round(nim * LUNA_PER_NIM), warrantyNote: d.get('note'), threshold: Number(d.get('threshold')) || 5, rewardDescription: d.get('reward') }) }); const b = await r.json(); if (!r.ok) throw new Error(b.error); setLink(`${window.location.origin}${b.checkoutPath}`); form.reset() }
  const submit = (fn: (form: HTMLFormElement) => Promise<void>) => (e: React.FormEvent<HTMLFormElement>) => { e.preventDefault(); setError(''); void fn(e.currentTarget).catch((x: Error) => setError(x.message)) }
  return <main className="app-shell merchant-page"><p className="eyebrow">Merchant workspace</p><h1>{merchantId ? 'Create a checkout' : 'Start selling with NIM.'}</h1><p className="page-intro">Create an item, share one link, then see the verified sale appear here.</p>
    {!merchantId ? <form className="form-card" onSubmit={submit(merchant)}><h2>Your receiving wallet</h2><label>Business name<input name="name" placeholder="Alike Coffee" required /></label><label>Nimiq receiving address<input name="wallet" placeholder="NQ…" required /></label><button>Create merchant profile</button></form> : <><form className="form-card" onSubmit={submit(checkout)}><h2>New payable purchase</h2><label>Item name<input name="item" placeholder="Flat white" required /></label><label>Price in NIM<input name="price" inputMode="decimal" placeholder="1.50" required /></label><label>Warranty or return note <em>optional</em><input name="note" placeholder="Ask us within 7 days" /></label><details><summary>Loyalty reward <em>optional</em></summary><label>Purchases needed<input name="threshold" inputMode="numeric" placeholder="5" /></label><label>Reward description<input name="reward" placeholder="Free coffee" /></label></details><button>Create checkout link</button></form>
    {link && <section className="share-card"><p className="eyebrow">Ready to share</p><h2>Checkout created</h2><p className="checkout-url">{link}</p><button onClick={() => void navigator.clipboard.writeText(link).then(() => setCopied(true))}>{copied ? 'Link copied' : 'Copy checkout link'}</button><a className="text-link" href={link}>Open checkout</a></section>}
    <section className="sales-section"><p className="eyebrow">Sales</p><h2>Recent purchases</h2>{sales.length ? <ul className="sales-list">{sales.map((sale) => <li key={sale.id}><span>{sale.itemSummary}</span><small>{sale.status.replaceAll('_', ' ')}</small></li>)}</ul> : <p className="empty-copy">Your verified sales will appear here after customers pay.</p>}</section></>}{error && <p className="form-error" role="alert">{error}</p>}</main>
}
